name: Dockerize and Push to Docker Hub

on:
  workflow_run:
    workflows: ["Run Tests updated"]
    types:
      - completed

jobs:
  dockerize:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build --no-cache  -t ${{ secrets.DOCKER_USERNAME }}/ecommercefrontend:$GITHUB_SHA -f webapp/Dockerfile ./webapp
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommercefrontend:$GITHUB_SHA

      # Step 5: Build and push backend image
      - name: Build and push backend image
        run: |
          docker build --no-cache  -t ${{ secrets.DOCKER_USERNAME }}/ecommercebackend:$GITHUB_SHA -f api/Dockerfile ./api
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommercebackend:$GITHUB_SHA
