version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3000
