name: CI Pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache backend dependencies
        uses: actions/cache@v3
        with:
          path: ./api/node_modules
          key: backend-dependencies-${{ runner.os }}-${{ hashFiles('./api/package.json', './api/package-lock.json') }}
          restore-keys: |
            backend-dependencies-${{ runner.os }}-

      - name: Install backend dependencies
        working-directory: ./api
        run: npm ci

      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: ./webapp/node_modules
          key: frontend-dependencies-${{ runner.os }}-${{ hashFiles('./webapp/package.json', './webapp/package-lock.json') }}
          restore-keys: |
            frontend-dependencies-${{ runner.os }}-

      - name: Install frontend dependencies
        working-directory: ./webapp
        run: npm ci

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run backend tests
        working-directory: ./api
        run: |
          npx jest

      - name: Run frontend tests
        working-directory: ./webapp
        run: |
          npx jest
