name: Run Tests

on:
  workflow_run:
    workflows: ["Install"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug current directory
        run: pwd

      - name: Debug folder structure
        run: ls -la

      # Backend (API) Tests
      - name: Run tests for backend (API)
        working-directory: ./api
        run: |
          npm ci
          npm test

      # Frontend (WebApp) Tests
      - name: Run tests for frontend (WebApp)
        working-directory: ./webapp
        run: |
          npm ci
          npm test
