name: Tests

on:
  workflow_run:
    workflows: ["Install"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug folder structure
        run: ls -R
        # Run ls recursively to show the entire directory tree

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'

      # Run Jest tests in webapp
      - name: Run Jest tests in webapp
        working-directory: ./webapp/__tests__
        run: npm test
      - name: Run Jest tests in backend
        working-directory: ./api/__tests__
        run: npm test
